#include <iostream>
#include <vector>
#include <string>
#include <iomanip>
#include <limits>
using namespace std;
class Book{int id;string title,author;bool issued;public:Book(int i,string t,string a):id(i),title(move(t)),author(move(a)),issued(false){}int getId()const{return id;}bool isIssued()const{return issued;}void issue(){issued=true;}void returnBook(){issued=false;}void display()const{cout<<left<<setw(6)<<id<<setw(28)<<title<<setw(22)<<author<<(issued?"Issued":"Available")<<'\n';}};
class Library{vector<Book> books;Book* findBook(int id){for(auto&b:books)if(b.getId()==id)return &b;return nullptr;}public:void addBook(){int id;string title,author;cout<<"Enter book ID: ";cin>>id;cin.ignore(numeric_limits<streamsize>::max(),'\n');cout<<"Enter title: ";getline(cin,title);cout<<"Enter author: ";getline(cin,author);if(findBook(id)){cout<<"ID already exists.\n";return;}books.emplace_back(id,title,author);cout<<"Book added.\n";}void listBooks()const{if(books.empty()){cout<<"No books.\n";return;}cout<<left<<setw(6)<<"ID"<<setw(28)<<"Title"<<setw(22)<<"Author"<<"Status\n";cout<<string(65,'-')<<'\n';for(const auto&b:books)b.display();}void issueBook(){int id;cout<<"Enter book ID: ";cin>>id;Book*b=findBook(id);if(!b)cout<<"Book not found.\n";else if(b->isIssued())cout<<"Already issued.\n";else{b->issue();cout<<"Book issued.\n";}}void returnBook(){int id;cout<<"Enter book ID: ";cin>>id;Book*b=findBook(id);if(!b)cout<<"Book not found.\n";else if(!b->isIssued())cout<<"Book is already available.\n";else{b->returnBook();cout<<"Book returned.\n";}}void run(){books.emplace_back(101,"The C++ Programming Language","Bjarne Stroustrup");books.emplace_back(102,"Clean Code","Robert C. Martin");int choice;do{cout<<"\n===== LIBRARY MANAGEMENT SYSTEM =====\n1. Add Book\n2. List Books\n3. Issue Book\n4. Return Book\n5. Exit\nChoose: ";cin>>choice;switch(choice){case 1:addBook();break;case 2:listBooks();break;case 3:issueBook();break;case 4:returnBook();break;case 5:cout<<"Goodbye!\n";break;default:cout<<"Invalid choice.\n";}}while(choice!=5);}};
int main(){Library library;library.run();}
